### ISSUE TITLE
Local group membership issue

### ISSUE THREAD

**Issue by Wikh** [SenseNet/sn-workspaces#3]
I have a workspace template with local groups referencing to each other. When creating a new workspace based on this template the group membership references under the new instance are not updated - so they still refer to the groups under the template.

**Comment by Wikh** [comment]
![template](https://user-images.githubusercontent.com/7532838/28664573-30b52ca8-72c1-11e7-8809-1ea03279e42f.png)

**Comment by tusmester** [comment]
We have to check the *ContentTemplate* class (in the *Services* component, *ContentRepository* project), most likely the *UpdateLocalReferences* method.

**Comment by borsi** [comment]
Waiting for Joe to confirm it works as intended

**Comment by VargaJoe** [comment]
Confirmed.

**Comment by tusmester** [comment]
(it was fixed by [this PR](https://github.com/SenseNet/sensenet/pull/136))
